# Generated by Django 3.0.5 on 2020-05-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_auto_20200502_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
